In [1]:
import pandas as pd

## 1-  Read the Dataset

In [ ]:
def Read_Data_File(file_path: str) -> pd.DataFrame:
    """
    This function reads a CSV file and returns a DataFrame.
    Parameters:
        file_path (str): The path to the CSV file.
    Returns:
        pd.DataFrame: The DataFrame containing the data from the CSV file.
    """
    try:
        return pd.read_csv(file_path)
    except FileNotFoundError:
        raise FileNotFoundError("ERROR: File is not found")
    except Exception as e:
        raise Exception(f"Could not read the file: {e}")

In [20]:
df1 = Read_Data_File("Titanic.csv")
df1.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [19]:
df2 = Read_Data_File("abc")

FileNotFoundError: ERROR: File is not found

## 2-  Remove Unnecessary Features

In [24]:
import config.config as c

def Drop_unnecessary_features(df:  pd.DataFrame, cols: list[str]) -> pd.DataFrame:
    """
    This function drops the specified columns from the given DataFrame.
    Parameters:
        df (pd.DataFrame): The DataFrame from which to drop columns.
        cols (list[str]): The list of column names to drop.
    Returns:
        pd.DataFrame: The DataFrame with the specified columns dropped.
    """

    df.drop(columns = cols, inplace = True)

In [ ]:
Drop_unnecessary_features(df1, c.COLS_TO_DROP)

['PassengerId', 'Name', 'Ticket']

     Survived  Pclass     Sex   Age  SibSp  Parch     Fare Cabin Embarked
0           0       3    male  22.0      1      0   7.2500   NaN        S
1           1       1  female  38.0      1      0  71.2833   C85        C
2           1       3  female  26.0      0      0   7.9250   NaN        S
3           1       1  female  35.0      1      0  53.1000  C123        S
4           0       3    male  35.0      0      0   8.0500   NaN        S
..        ...     ...     ...   ...    ...    ...      ...   ...      ...
886         0       2    male  27.0      0      0  13.0000   NaN        S
887         1       1  female  19.0      0      0  30.0000   B42        S
888         0       3  female   NaN      1      2  23.4500   NaN        S
889         1       1    male  26.0      0      0  30.0000  C148        C
890         0       3    male  32.0      0      0   7.7500   NaN        Q

[891 rows x 9 columns]

## 3- Check Data Type

In [32]:
def Check_data_type(df: pd.DataFrame):
    dtypes = df.dtypes
    num_of_unique = df.nunique()
    return pd.DataFrame({"Dtypes": dtypes, "Unique Values": num_of_unique}).T

In [33]:
Check_data_type(df1)

,Survived,Pclass,Sex,Age,SibSp,Parch,Fare,Cabin,Embarked
Dtypes,int64,int64,str,float64,int64,int64,float64,str,str
Unique Values,2,3,2,88,7,7,248,147,3